---
default:
  endpoint: "https://api.example.com/default"
  delete-message: false
  messageid-pattern: "([A-Z0-9]{12})"

rules:
  - name: "Server blocked"
    pattern: "due to IP address restrictions"
    endpoint: "https://api.example.com/bounce"

  - name: "Mailbox full"
    pattern: "mailbox full"
    delete-message: true
