name: Build and Release Tarball

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux-x64, linux-arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install .

      - name: Prepare tarball directory
        run: |
          mkdir -p dist/postfix-watcher/bin
          mkdir -p dist/postfix-watcher/config
          mkdir -p dist/postfix-watcher/systemd

          cp pyproject.toml dist/postfix-watcher/                    
          cp README.md dist/postfix-watcher/ || true                 
          cp LICENSE dist/postfix-watcher/
          cp -r postfix_watcher dist/postfix-watcher/                
          cp systemd/postfix-watcher.service dist/postfix-watcher/systemd/
          cp config/postfix-watcher.yaml.dist dist/postfix-watcher/config/

          # Create wrapper script
          echo "#!/bin/bash" > dist/postfix-watcher/bin/postfix-watcher
          echo "exec python3 -m postfix_watcher.watcher \"\$@\"" >> dist/postfix-watcher/bin/postfix-watcher
          chmod +x dist/postfix-watcher/bin/postfix-watcher


      - name: Create tarball
        run: |
          cd dist
          tar -czf postfix-watcher-${{ github.ref_name }}-${{ matrix.platform }}.tar.gz postfix-watcher
          cd ..

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/postfix-watcher-${{ github.ref_name }}-${{ matrix.platform }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}